# Generated by Django 5.2.4 on 2025-08-01 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kudos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="The organization to which the user belongs.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="kudos.organization",
            ),
        ),
    ]
