# Generated by Django 5.2.4 on 2025-08-01 06:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kudos", "0002_alter_user_organization"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kudo",
            name="timestamp",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="The date and time when the kudo was sent.",
            ),
        ),
    ]
